"""Adding user id and changing foreign key references from email to id

Revision ID: 1735d65236e0
Revises: 1e514d930219
Create Date: 2025-05-08 16:55:25.781205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1735d65236e0'
down_revision = '1e514d930219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False))
        batch_op.drop_constraint('uix_user_unit_sem', type_='unique')
        batch_op.create_unique_constraint('uix_user_unit_sem', ['user_id', 'unit_id', 'semester'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_email')

    with op.batch_alter_table('diary_shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.String(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['recipient_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])
        batch_op.drop_column('owner_email')
        batch_op.drop_column('recipient_email')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('study_field', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('study_field')
        batch_op.drop_column('username')
        batch_op.drop_column('id')

    with op.batch_alter_table('diary_shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_email', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('owner_email', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_email'], ['email'])
        batch_op.create_foreign_key(None, 'users', ['recipient_email'], ['email'])
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_email'], ['email'])
        batch_op.drop_constraint('uix_user_unit_sem', type_='unique')
        batch_op.create_unique_constraint('uix_user_unit_sem', ['user_email', 'unit_id', 'semester'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
