"""Add university_id to Unit model

Revision ID: 1e514d930219
Revises: 641c58f9dcfc
Create Date: 2025-05-07 16:31:39.040250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e514d930219'
down_revision = '641c58f9dcfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.alter_column('semester',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_units_university_id', 'universities', ['university_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('university_id')

    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('year')

    # ### end Alembic commands ###
