"""empty message

Revision ID: 1fa03898cb61
Revises: 1735d65236e0
Create Date: 2025-05-12 19:42:49.168247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa03898cb61'
down_revision = '1735d65236e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optional_comments', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.drop_column('optional_comments')

    # ### end Alembic commands ###
