"""Initial schema: users, units, diary, shares

Revision ID: 641c58f9dcfc
Revises: 
Create Date: 2025-05-05 00:04:40.884099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641c58f9dcfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('diary_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_email', sa.String(length=64), nullable=False),
    sa.Column('recipient_email', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['owner_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['recipient_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('diary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=64), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('difficulty_rating', sa.Integer(), nullable=True),
    sa.Column('coordinator_rating', sa.Integer(), nullable=True),
    sa.Column('workload_hours_per_week', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'unit_id', 'semester', name='uix_user_unit_sem')
    )
    op.create_table('assessment_breakdowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['diary_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_breakdowns')
    op.drop_table('diary_entries')
    op.drop_table('units')
    op.drop_table('faculties')
    op.drop_table('diary_shares')
    op.drop_table('users')
    op.drop_table('universities')
    # ### end Alembic commands ###
