"""Add assessment types and unit assessment types tables

Revision ID: 6787f24efd01
Revises: 1fa03898cb61
Create Date: 2025-05-14 08:39:48.232178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6787f24efd01'
down_revision = '1fa03898cb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unit_assessment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_type_id'], ['assessment_types.id'], name='fk_unit_assessment_types_assessment_types_assessment_type_id'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name='fk_unit_assessment_types_units_unit_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'assessment_type_id', name='uix_unit_assessment_type')
    )
    op.drop_table('assessment_breakdowns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_breakdowns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entry_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('percentage', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['diary_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('unit_assessment_types')
    op.drop_table('assessment_types')
    # ### end Alembic commands ###
