"""Migrating user_email to user_id in diary_entries

Revision ID: a66d424c0d31
Revises: f05342b8e682
Create Date: 2025-05-14 13:38:32.446562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66d424c0d31'
down_revision = 'f05342b8e682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        op.execute(
            "UPDATE diary_entries SET user_id = (SELECT id FROM users WHERE users.email = diary_entries.user_email)"
        )
        # Alter the user_id column to be NOT NULL
        batch_op.alter_column('user_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(length=64), nullable=False))
        op.execute("UPDATE diary_entries SET user_email = (SELECT email FROM users WHERE users.id = diary_entries.user_id)")
        batch_op.create_foreign_key('fk_diary_entries_user_email_users', 'users', ['user_email'], ['email'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
