"""Switch FK from user_email to user_id in diary_shares and diary_entries

Revision ID: f05342b8e682
Revises: 1735d65236e0
Create Date: 2025-05-13 01:34:45.150376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05342b8e682'
down_revision = '1735d65236e0'
branch_labels = None
depends_on = None

# NOTE: manually removed FK constraint drop commands
# -> FK constraint dropped implicitly via column removal (SQLite doesn’t store constraint names)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('uix_user_unit_sem', type_='unique')
        batch_op.create_unique_constraint('uix_user_unit_sem', ['user_id', 'unit_id', 'semester'])
        #manually removed: batch_op.drop_constraint('fk_diary_entries_users_user_email', type_='foreignkey')
        batch_op.create_foreign_key('fk_diary_entries_users_user_id', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_email')

    with op.batch_alter_table('diary_shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        #manually removed: batch_op.drop_constraint('fk_diary_shares_users_owner_email', type_='foreignkey')          
        #manually removed: batch_op.drop_constraint('fk_diary_shares_users_recipient_email', type_='foreignkey')  
        batch_op.create_foreign_key('fk_diary_shares_users_owner_id', 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key('fk_diary_shares_users_recipient_id', 'users', ['recipient_id'], ['id'])
        batch_op.drop_column('owner_email')
        batch_op.drop_column('recipient_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_email', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('owner_email', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint('fk_diary_shares_users_recipient_id', type_='foreignkey') 
        batch_op.drop_constraint('fk_diary_shares_users_owner_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['recipient_email'], ['email'])
        batch_op.create_foreign_key(None, 'users', ['owner_email'], ['email'])
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint('fk_diary_entries_users_user_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_email'], ['email'])
        batch_op.drop_constraint('uix_user_unit_sem', type_='unique')
        batch_op.create_unique_constraint('uix_user_unit_sem', ['user_email', 'unit_id', 'semester'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
